//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Story = newStoryTable("hmb", "story", "")

type storyTable struct {
	postgres.Table

	// Columns
	StoryID   postgres.ColumnString
	Title     postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type StoryTable struct {
	storyTable

	EXCLUDED storyTable
}

// AS creates new StoryTable with assigned alias
func (a StoryTable) AS(alias string) *StoryTable {
	return newStoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StoryTable with assigned schema name
func (a StoryTable) FromSchema(schemaName string) *StoryTable {
	return newStoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new StoryTable with assigned table prefix
func (a StoryTable) WithPrefix(prefix string) *StoryTable {
	return newStoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new StoryTable with assigned table suffix
func (a StoryTable) WithSuffix(suffix string) *StoryTable {
	return newStoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newStoryTable(schemaName, tableName, alias string) *StoryTable {
	return &StoryTable{
		storyTable: newStoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newStoryTableImpl("", "excluded", ""),
	}
}

func newStoryTableImpl(schemaName, tableName, alias string) storyTable {
	var (
		StoryIDColumn   = postgres.StringColumn("story_id")
		TitleColumn     = postgres.StringColumn("title")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{StoryIDColumn, TitleColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{TitleColumn, CreatedAtColumn}
	)

	return storyTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		StoryID:   StoryIDColumn,
		Title:     TitleColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
